<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>4.0.0</Version>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>    
  <RootNamespace>GPC.Model</RootNamespace>    
  <Configurations>Debug;Release;DebugLocalLibs</Configurations>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Materials\Aluminium\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DelaunayMesh">
      <HintPath>..\..\Geometry\DelaunayMesh\bin\Release\netstandard2.0\DelaunayMesh.dll</HintPath>
    </Reference>
    <Reference Include="GPCGeometry">
      <HintPath>..\..\Geometry\GPCGeometry\bin\Release\netstandard2.0\GPCGeometry.dll</HintPath>
    </Reference>
    <Reference Include="GPCUtilities">
      <HintPath>..\..\Utilities\GPCUtilities\bin\Release\netstandard2.0\GPCUtilities.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
