using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using GPC.Converter;
using GPC.Converter.Straus7;
using GPC.Geometry;
using GPC.Model.Loads;
using GPC.Model.PostProcessing;
using GPC.Model.Results.ResultLocations;
using GPC.Model.Sections;
using GPC.Model.Sections.Concrete;
using GPC.Model.Sections.Steel;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTest;

[TestClass]
public class Straus7NativeIntegrationTest
{
    // Opt-in: generated by Fixtures/Straus7/generate_native_fixture.py using the actual solver.
    // No DLL/licence or native file is required for the default deterministic test suite.
    [TestMethod, TestCategory("Straus7Native")]
    public void NativeLinearStaticBenchmark_EquilibriumAndMembraneResultants()
    {
        var folder = Environment.GetEnvironmentVariable("GPC_STRAUS7_BENCHMARK");
        if (string.IsNullOrWhiteSpace(folder)) Assert.Inconclusive("Set GPC_STRAUS7_BENCHMARK to the newly generated native fixture directory.");
        var path = Path.Combine(folder!, "benchmark.st7"); var resultPath = Path.Combine(folder!, "benchmark.LSA");
        var converter = new Straus7ApiConverter();
        var geometry = converter.Import(new Straus7ImportRequest { ModelPath = path, ModelRevision = "native-benchmark-v1", AnalysisId = "lsa-1" });
        Assert.IsNotNull(geometry.Model, string.Join(";", geometry.Diagnostics.Select(d => d.Message)));
        var model = geometry.Model;
        Assert.AreEqual(6, model.NodesElements.Count); Assert.AreEqual(1, model.BeamElements.Count); Assert.AreEqual(1, model.AreaElements.Count);
        var native = converter.ReadResults(new Straus7ResultsRequest { ModelPath = path, ResultPath = resultPath,
            CaseNumbers = new[] { 1, 2 }, BeamNumbers = new[] { 1 }, PlateNumbers = new[] { 1 }, NodeNumbers = new[] { 1, 2, 3, 4, 5, 6 },
            MinimumBeamStations = 3, IncludeElementNodeForces = true });
        Assert.AreEqual(ImportStatus.Completed, native.Status, string.Join(";", native.Diagnostics.Select(d => d.Message)));
        foreach (var table in native.Tables) Console.WriteLine($"{table.Quantity}: {table.Rows}x{table.Columns}; positions={string.Join(",", table.Positions ?? Array.Empty<double>())}; values={string.Join(",", table.Values)}; state={string.Join(",", table.ElementState ?? Array.Empty<int>())}");
        // Equilibrium of the negative cut face of a 2000-mm cantilever along global Z:
        // Ftip=(100,200,300), Mtip=(10,20,30), Mpositive=Mtip+(0,0,L-z) x Ftip.
        var raw = native.Tables.Single(t => t.Quantity == "BeamForceGlobal" && t.CaseNumber == 1);
        Assert.AreEqual(6, raw.Columns);
        for (int row = 0; row < raw.Rows; row++)
        {
            double arm = 2000 * (1 - raw.Positions[row]);
            var expected = new[] { -100d, 200 * arm - 10, -200d, -100 * arm - 20, -300d, -30d };
            for (int col = 0; col < 6; col++) Assert.AreEqual(expected[col], raw.Values[row * 6 + col], 1e-6, $"Native beam row {row} column {col}");
        }
        // A positive global Y end couple gives tension on the +z face: native Mxx=+1 Nmm/mm.
        var bending = native.Tables.Single(t => t.Quantity == "PlateMomentLocalCentroid" && t.CaseNumber == 2);
        Assert.AreEqual(1, bending.Values[0], 1e-8); Assert.AreEqual(0, bending.Values[1], 1e-8); Assert.AreEqual(0, bending.Values[3], 1e-8);
        var imported = Straus7LinearStaticResults.Import(model, native, "native-benchmark", new Dictionary<int, string> { [1] = "Case 1: Benchmark", [2] = "Case 2: Bending" });
        Assert.AreEqual(ImportStatus.Completed, imported.Status, string.Join(";", imported.Diagnostics.Select(d => d.Message)));
        var beam = model.BeamElements.Values.Single(); var axes = beam.Assignments.SectionAxes;
        foreach (var sample in Verification.BeamSamples(beam, "native-benchmark", "Case 1: Benchmark"))
        {
            var f = sample.ResultBeamForces;
            Vector3d globalForce = axes.V1 * f.V1 + axes.V2 * f.V2 + axes.V3 * f.N;
            Vector3d globalMoment = axes.V1 * f.M1 + axes.V2 * f.M2 + axes.V3 * f.T;
            Assert.AreEqual(100, globalForce.X, 1e-6); Assert.AreEqual(200, globalForce.Y, 1e-6); Assert.AreEqual(300, globalForce.Z, 1e-6);
            Assert.IsTrue(sample.PhysicalDistance.HasValue);
            double arm = 2000 - sample.PhysicalDistance.GetValueOrDefault();
            Assert.AreEqual(10 - 200 * arm, globalMoment.X, 1e-6); Assert.AreEqual(20 + 100 * arm, globalMoment.Y, 1e-6); Assert.AreEqual(30, globalMoment.Z, 1e-6);
            Assert.AreNotEqual(DataStatus.Ready, Verification.PrepareBeam(model, beam.Id, sample, "native benchmark").Status);
        }
        var plateSamples = model.AreaElements.Values.Single().Results.SelectMany(r => r.Results).OfType<PointResultPlateForces>().ToArray();
        Assert.AreEqual(2, plateSamples.Length);
        var plate = plateSamples.Single(p => Math.Abs(p.Forces.Fxx - 1) < 1e-8).Forces;
        Assert.AreEqual(1, plateSamples.Single(p => Math.Abs(p.Forces.Fxx) < 1e-8).Forces.Mxx, 1e-8);
        // Two 500-N nodal forces across a 1000-mm-wide membrane with nu=0.
        Assert.AreEqual(1, plate.Fxx, 1e-8); Assert.AreEqual(0, plate.Fyy, 1e-8); Assert.AreEqual(0, plate.Fxy, 1e-8);
        Assert.AreEqual(0, plate.Fxz, 1e-8); Assert.AreEqual(0, plate.Fyz, 1e-8);
        Assert.AreEqual(0, plate.Mxx, 1e-8); Assert.AreEqual(0, plate.Myy, 1e-8); Assert.AreEqual(0, plate.Mxy, 1e-8);
        var selection = new ResultSelection { Dataset = "native-benchmark", Case = "Case 1: Benchmark" };
        var iNode = beam.NodeI; var jNode = beam.NodeJ; var owner = new ElementKey { Family = EntityFamily.Beam, Id = beam.Id };
        var reaction = ResultQueries.NodeForce(iNode, selection, NodalForceKind.SupportReaction, ActionBody.OnNode);
        Assert.AreEqual(-100, reaction.Fx, 1e-6); Assert.AreEqual(399990, reaction.Mx, 1e-6);
        var endI = ResultQueries.NodeForce(iNode, selection, NodalForceKind.ElementEndForce, ActionBody.OnElement, owner, "I");
        var endJ = ResultQueries.NodeForce(jNode, selection, NodalForceKind.ElementEndForce, ActionBody.OnElement, owner, "J");
        Assert.AreEqual(-100, endI.Fx, 1e-6); Assert.AreEqual(399990, endI.Mx, 1e-6);
        Assert.AreEqual(100, endJ.Fx, 1e-6); Assert.AreEqual(10, endJ.Mx, 1e-6);
        var d = ResultQueries.Samples<NodeResultDisplacement>(jNode, selection).Single().ResultDisplacement;
        Assert.AreEqual(300 * 2000d / (200 * 300 * 30000), d.D3, 1e-12);
        // Independent Euler-Bernoulli end rotations for the uncoupled rectangular beam (no transverse-shear term).
        Assert.AreEqual(-2.962814814814815e-5, d.R1, 1e-12); Assert.AreEqual(3.334e-5, d.R2, 1e-12);
        var plateElement = model.AreaElements.Values.Single();
        foreach (var node in plateElement.Nodes)
        {
            var force = ResultQueries.NodeForce(node, selection, NodalForceKind.ElementNodeForce, ActionBody.OnElement,
                new ElementKey { Family = EntityFamily.Shell, Id = plateElement.Id });
            Assert.AreEqual(node.Position.X < 3500 ? -500 : 500, force.Fx, 1e-6);
        }
        var prepared = ResultPreparation.Prepare(model, new ElementSelection { Families = new[] { EntityFamily.Node, EntityFamily.Beam, EntityFamily.Shell } }, new[] { selection });
        Assert.AreEqual(22, prepared.Count);
        Assert.IsTrue(prepared.All(p => p.IsCurrent), string.Join(";", prepared.SelectMany(p => p.Diagnostics).Select(diagnostic => diagnostic.Message)));
    }

    // Opt-in: generated by Fixtures/Straus7/generate_native_assignments_fixture.py. The imported loads must reproduce the totals of
    // the solver and balance its support reactions, offsets and the eccentric girder loads included.
    [TestMethod, TestCategory("Straus7Native")]
    public void NativeAssignments_LoadsAndGravityBalanceTheSolverReactions()
    {
        var folder = Environment.GetEnvironmentVariable("GPC_STRAUS7_ASSIGNMENTS");
        if (string.IsNullOrWhiteSpace(folder)) Assert.Inconclusive("Set GPC_STRAUS7_ASSIGNMENTS to the newly generated native assignments fixture directory.");
        var path = Path.Combine(folder!, "assignments.st7"); var resultPath = Path.Combine(folder!, "assignments.LSA");
        var converter = new Straus7ApiConverter();
        var geometry = converter.Import(new Straus7ImportRequest { ModelPath = path, ModelRevision = "native-assignments-v1", AnalysisId = "lsa-1" });
        Assert.AreEqual(ImportStatus.Partial, geometry.Status, string.Join(";", geometry.Diagnostics.Select(d => d.Code + ": " + d.Message)));
        var model = geometry.Model;
        Assert.AreEqual(8, model.NodesElements.Count); Assert.AreEqual(3, model.BeamElements.Count); Assert.AreEqual(2, model.AreaElements.Count);
        Assert.IsFalse(geometry.Diagnostics.Any(d => d.Code == "Straus7SectionByValues"), "Both standard sections must be recognised.");
        foreach (var column in new[] { "1", "2" })
            Assert.IsInstanceOfType(((ReinforcedConcreteSection)model.BeamElements.Values.Single(b => b.Source.OriginalId == column).BeamProperty).SectionShape, typeof(SectionRectangular));
        var girder = model.BeamElements.Values.Single(b => b.Source.OriginalId == "3");
        Assert.IsInstanceOfType(((SteelSection)girder.BeamProperty).SectionShape, typeof(SectionH));
        Assert.AreEqual(0, girder.Assignments.SectionCentroidOffset.X, 1e-12); Assert.AreEqual(100, girder.Assignments.SectionCentroidOffset.Y, 1e-12);
        var thick = model.AreaElements.Values.Single(s => s.Source.OriginalId == "2");
        Assert.AreEqual(250, thick.Assignments.PhysicalThickness); Assert.AreEqual(50, thick.Assignments.Offset);
        Assert.AreEqual(6, model.NodesElements.Values.Count(n => n.Assignments.Restrains.Count == 1));

        // Results chosen after the import and read for the whole model, with the cases mapped by name.
        var native = converter.ReadResults(model, ResultFilter.All(model), path, resultPath);
        Assert.AreEqual(ImportStatus.Completed, native.Status, string.Join(";", native.Diagnostics.Select(d => d.Message)));
        var cases = new Dictionary<int, string> { [1] = Straus7ApiConverter.CaseName(1, "Loads"), [2] = Straus7ApiConverter.CaseName(2, "Gravity") };
        CollectionAssert.AreEquivalent(cases.ToArray(), Straus7LinearStaticResults.CaseMap(model, native.Cases).ToArray());
        var imported = Straus7LinearStaticResults.Import(model, native, "native-assignments");
        Assert.AreEqual(ImportStatus.Completed, imported.Status, string.Join(";", imported.Diagnostics.Select(d => d.Message)));

        // Solver totals of the applied loads (Straus7 load summary of the fixture).
        var totals = new Dictionary<string, Vector3d> { [cases[1]] = new Vector3d(4150, -41000, -134000), [cases[2]] = new Vector3d(0, 0, 237484) };
        foreach (var name in cases.Values)
        {
            var contributions = new List<EquilibriumContribution>();
            foreach (var node in model.NodesElements.Values)
                contributions.AddRange(node.Loads.Values.OfType<PointLoad>().Where(l => l.LoadCase.Name == name).Select(l => Equilibrium.PointLoad(l, "node")));
            foreach (var beam in model.BeamElements.Values)
                contributions.AddRange(beam.Assignments.Loads.Where(l => (l.Concentrated?.LoadCase ?? l.StartIntensity.LoadCase).Name == name).Select(l => Equilibrium.BeamLoad(beam, l)));
            foreach (var shell in model.AreaElements.Values)
                foreach (var l in shell.Loads.Values.Where(l => l.LoadCase.Name == name))
                {
                    var traction = l switch { NormalAreaLoad n => n.GetGlobalLoadVector() / n.Shape.GetArea(),
                        AreaLoad a => a.CoordinateSystem.V1 * a.P1 + a.CoordinateSystem.V2 * a.P2 + a.CoordinateSystem.V3 * a.P3, _ => throw new AssertFailedException("Unexpected shell load " + l.GetType().Name) };
                    contributions.Add(Equilibrium.ShellPressure(shell, traction, name, "pressure", "pressure"));
                }
            contributions.AddRange(model.ModelLoads.Values.OfType<ModelGravityLoad>().Where(g => g.LoadCase.Name == name).Select(g => Equilibrium.Gravity(model, g, "gravity")));
            var applied = Sum(contributions);
            Assert.AreEqual(totals[name].X, applied.Force.X, 0.5, name); Assert.AreEqual(totals[name].Y, applied.Force.Y, 0.5, name); Assert.AreEqual(totals[name].Z, applied.Force.Z, 0.5, name);
            var reactions = model.NodesElements.Values.SelectMany(n => n.Results.SelectMany(r => r.Results)).OfType<NodeResultForces>()
                .Where(r => r.Case?.Name == name && r.Kind == NodalForceKind.SupportReaction).ToArray();
            Assert.AreEqual(8, reactions.Length, name);
            foreach (var free in model.NodesElements.Values.Where(n => n.Assignments.Restrains.Count == 0))
                foreach (var r in free.Results.SelectMany(s => s.Results).OfType<NodeResultForces>().Where(r => r.Case?.Name == name && r.Kind == NodalForceKind.SupportReaction))
                    Assert.AreEqual(0, Math.Abs(r.Fx) + Math.Abs(r.Fy) + Math.Abs(r.Fz) + Math.Abs(r.Mx) + Math.Abs(r.My) + Math.Abs(r.Mz), 1e-6, "Free node " + free.Source.OriginalId);
            contributions.AddRange(reactions.Select(r => { var axes = r.ResultBeamForces.CoordinateSystem;
                return Equilibrium.Explicit("reaction", "reported", name, axes.Origin, axes.V1 * r.Fx + axes.V2 * r.Fy + axes.V3 * r.Fz, axes.V1 * r.Mx + axes.V2 * r.My + axes.V3 * r.Mz, "reaction"); }));
            var residual = Sum(contributions);
            Assert.AreEqual(0, Axes.Length(residual.Force), 1e-6, name + " force residual");
            Assert.AreEqual(0, Axes.Length(residual.Moment), 1e-2, name + " moment residual (about the origin, Nmm)");
        }
    }

    private static (Vector3d Force, Vector3d Moment) Sum(IEnumerable<EquilibriumContribution> contributions)
    {
        Vector3d force = new Vector3d(0, 0, 0), moment = new Vector3d(0, 0, 0);
        foreach (var c in contributions) { force += c.Force; moment += c.Moment + ((Vector3d)c.Point).CrossProduct(c.Force); }
        return (force, moment);
    }
}
