using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using GPC.Converter;
using GPC.Converter.Straus7;
using GPC.Geometry;
using GPC.Model.PostProcessing;
using GPC.Model.Results.ResultLocations;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTest;

[TestClass]
public class Straus7NativeIntegrationTest
{
    // Opt-in: generated by Fixtures/Straus7/generate_native_fixture.py using the actual solver.
    // No DLL/licence or native file is required for the default deterministic test suite.
    [TestMethod, TestCategory("Straus7Native")]
    public void NativeLinearStaticBenchmark_EquilibriumAndMembraneResultants()
    {
        var folder = Environment.GetEnvironmentVariable("GPC_STRAUS7_BENCHMARK");
        if (string.IsNullOrWhiteSpace(folder)) Assert.Inconclusive("Set GPC_STRAUS7_BENCHMARK to the newly generated native fixture directory.");
        var path = Path.Combine(folder!, "benchmark.st7"); var resultPath = Path.Combine(folder!, "benchmark.LSA");
        var converter = new Straus7ApiConverter();
        var geometry = converter.Import(new Straus7ImportRequest { ModelPath = path, ModelRevision = "native-benchmark-v1", AnalysisId = "lsa-1" });
        Assert.IsNotNull(geometry.Model, string.Join(";", geometry.Diagnostics.Select(d => d.Message)));
        var model = geometry.Model;
        Assert.AreEqual(6, model.NodesElements.Count); Assert.AreEqual(1, model.BeamElements.Count); Assert.AreEqual(1, model.AreaElements.Count);
        var native = converter.ReadResults(new Straus7ResultsRequest { ModelPath = path, ResultPath = resultPath,
            CaseNumbers = new[] { 1, 2 }, BeamNumbers = new[] { 1 }, PlateNumbers = new[] { 1 }, NodeNumbers = new[] { 1, 2, 3, 4, 5, 6 },
            MinimumBeamStations = 3, IncludeElementNodeForces = true });
        Assert.AreEqual(ImportStatus.Completed, native.Status, string.Join(";", native.Diagnostics.Select(d => d.Message)));
        foreach (var table in native.Tables) Console.WriteLine($"{table.Quantity}: {table.Rows}x{table.Columns}; positions={string.Join(",", table.Positions ?? Array.Empty<double>())}; values={string.Join(",", table.Values)}; state={string.Join(",", table.ElementState ?? Array.Empty<int>())}");
        // Equilibrium of the negative cut face of a 2000-mm cantilever along global Z:
        // Ftip=(100,200,300), Mtip=(10,20,30), Mpositive=Mtip+(0,0,L-z) x Ftip.
        var raw = native.Tables.Single(t => t.Quantity == "BeamForceGlobal" && t.CaseNumber == 1);
        Assert.AreEqual(6, raw.Columns);
        for (int row = 0; row < raw.Rows; row++)
        {
            double arm = 2000 * (1 - raw.Positions[row]);
            var expected = new[] { -100d, 200 * arm - 10, -200d, -100 * arm - 20, -300d, -30d };
            for (int col = 0; col < 6; col++) Assert.AreEqual(expected[col], raw.Values[row * 6 + col], 1e-6, $"Native beam row {row} column {col}");
        }
        // A positive global Y end couple gives tension on the +z face: native Mxx=+1 Nmm/mm.
        var bending = native.Tables.Single(t => t.Quantity == "PlateMomentLocalCentroid" && t.CaseNumber == 2);
        Assert.AreEqual(1, bending.Values[0], 1e-8); Assert.AreEqual(0, bending.Values[1], 1e-8); Assert.AreEqual(0, bending.Values[3], 1e-8);
        var imported = Straus7LinearStaticResults.Import(model, native, "native-benchmark", new Dictionary<int, string> { [1] = "Case 1: Benchmark", [2] = "Case 2: Bending" });
        Assert.AreEqual(ImportStatus.Completed, imported.Status, string.Join(";", imported.Diagnostics.Select(d => d.Message)));
        var beam = model.BeamElements.Values.Single(); var axes = beam.Assignments.SectionAxes;
        foreach (var sample in Verification.BeamSamples(beam, "native-benchmark", "Case 1: Benchmark"))
        {
            var f = sample.ResultBeamForces;
            Vector3d globalForce = axes.V1 * f.V1 + axes.V2 * f.V2 + axes.V3 * f.N;
            Vector3d globalMoment = axes.V1 * f.M1 + axes.V2 * f.M2 + axes.V3 * f.T;
            Assert.AreEqual(100, globalForce.X, 1e-6); Assert.AreEqual(200, globalForce.Y, 1e-6); Assert.AreEqual(300, globalForce.Z, 1e-6);
            Assert.IsTrue(sample.PhysicalDistance.HasValue);
            double arm = 2000 - sample.PhysicalDistance.GetValueOrDefault();
            Assert.AreEqual(10 - 200 * arm, globalMoment.X, 1e-6); Assert.AreEqual(20 + 100 * arm, globalMoment.Y, 1e-6); Assert.AreEqual(30, globalMoment.Z, 1e-6);
            Assert.AreNotEqual(DataStatus.Ready, Verification.PrepareBeam(model, beam.Id, sample, "native benchmark").Status);
        }
        var plateSamples = model.AreaElements.Values.Single().Results.SelectMany(r => r.Results).OfType<PointResultPlateForces>().ToArray();
        Assert.AreEqual(2, plateSamples.Length);
        var plate = plateSamples.Single(p => Math.Abs(p.Forces.Fxx - 1) < 1e-8).Forces;
        Assert.AreEqual(1, plateSamples.Single(p => Math.Abs(p.Forces.Fxx) < 1e-8).Forces.Mxx, 1e-8);
        // Two 500-N nodal forces across a 1000-mm-wide membrane with nu=0.
        Assert.AreEqual(1, plate.Fxx, 1e-8); Assert.AreEqual(0, plate.Fyy, 1e-8); Assert.AreEqual(0, plate.Fxy, 1e-8);
        Assert.AreEqual(0, plate.Fxz, 1e-8); Assert.AreEqual(0, plate.Fyz, 1e-8);
        Assert.AreEqual(0, plate.Mxx, 1e-8); Assert.AreEqual(0, plate.Myy, 1e-8); Assert.AreEqual(0, plate.Mxy, 1e-8);
        var selection = new ResultSelection { Dataset = "native-benchmark", Case = "Case 1: Benchmark" };
        var iNode = beam.NodeI; var jNode = beam.NodeJ; var owner = new ElementKey { Family = EntityFamily.Beam, Id = beam.Id };
        var reaction = ResultQueries.NodeForce(iNode, selection, NodalForceKind.SupportReaction, ActionBody.OnNode);
        Assert.AreEqual(-100, reaction.Fx, 1e-6); Assert.AreEqual(399990, reaction.Mx, 1e-6);
        var endI = ResultQueries.NodeForce(iNode, selection, NodalForceKind.ElementEndForce, ActionBody.OnElement, owner, "I");
        var endJ = ResultQueries.NodeForce(jNode, selection, NodalForceKind.ElementEndForce, ActionBody.OnElement, owner, "J");
        Assert.AreEqual(-100, endI.Fx, 1e-6); Assert.AreEqual(399990, endI.Mx, 1e-6);
        Assert.AreEqual(100, endJ.Fx, 1e-6); Assert.AreEqual(10, endJ.Mx, 1e-6);
        var d = ResultQueries.Samples<NodeResultDisplacement>(jNode, selection).Single().ResultDisplacement;
        Assert.AreEqual(300 * 2000d / (200 * 300 * 30000), d.D3, 1e-12);
        // Independent Euler-Bernoulli end rotations for the uncoupled rectangular beam (no transverse-shear term).
        Assert.AreEqual(-2.962814814814815e-5, d.R1, 1e-12); Assert.AreEqual(3.334e-5, d.R2, 1e-12);
        var plateElement = model.AreaElements.Values.Single();
        foreach (var node in plateElement.Nodes)
        {
            var force = ResultQueries.NodeForce(node, selection, NodalForceKind.ElementNodeForce, ActionBody.OnElement,
                new ElementKey { Family = EntityFamily.Shell, Id = plateElement.Id });
            Assert.AreEqual(node.Position.X < 3500 ? -500 : 500, force.Fx, 1e-6);
        }
        var prepared = ResultPreparation.Prepare(model, new ElementSelection { Families = new[] { EntityFamily.Node, EntityFamily.Beam, EntityFamily.Shell } }, new[] { selection });
        Assert.AreEqual(22, prepared.Count);
        Assert.IsTrue(prepared.All(p => p.IsCurrent), string.Join(";", prepared.SelectMany(p => p.Diagnostics).Select(diagnostic => diagnostic.Message)));
    }
}
