<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
	<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
	<Configurations>Debug;Release;DebugLocalLibs</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugLocalLibs|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GPC.Model.Persistence/GPC.Model.Persistence.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Examples\MixedModelFactory.cs" Link="Fixtures\MixedModelFactory.cs" />
    <Compile Include="../tests/CivilNxBoundaryTest.cs" Link="CivilNxBoundaryTest.cs" />
    <None Update="Fixtures\*.xml.gz" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Fixtures\Namespaces-v3\*" CopyToOutputDirectory="PreserveNewest" />
    <ProjectReference Include="..\ModelData\GPCModelData.csproj" />
    <ProjectReference Include="..\Model\GPCModel.csproj" />
    <ProjectReference Include="..\GPC Converter\GPC Converter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DelaunayMesh">
      <HintPath>..\..\Geometry\DelaunayMesh\bin\Release\netstandard2.0\DelaunayMesh.dll</HintPath>
    </Reference>
    <Reference Include="GMsh.Net">
      <HintPath>..\..\Gmsh.Net\src\GMsh.Net\bin\Release\netstandard2.0\GMsh.Net.dll</HintPath>
    </Reference>
    <Reference Include="GPCGeometry">
      <HintPath>..\..\Geometry\GPCGeometry\bin\Release\netstandard2.0\GPCGeometry.dll</HintPath>
    </Reference>
    <Reference Include="GPCUtilities">
      <HintPath>..\..\Utilities\GPCUtilities\bin\Release\netstandard2.0\GPCUtilities.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
