<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>GPC.Converter</RootNamespace>
    <AssemblyName>GPC.Converter</AssemblyName>
    <Version>1.0.2</Version>
    <Configurations>Debug;Release;DebugLocalLibs</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Model\GPCModel.csproj" />
    <ProjectReference Include="..\ModelData\GPCModelData.csproj" />
    <Reference Include="GPCGeometry">
      <HintPath>..\..\Geometry\GPCGeometry\bin\Release\netstandard2.0\GPCGeometry.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
