<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>    
  <RootNamespace>GPC.Model</RootNamespace>    
  <Configurations>Debug;Release;DebugLocalLibs</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FiniteElementAnalysis\FiniteElements\Brick\**" />
    <Compile Remove="FiniteElementAnalysis\FiniteElements\Plate\**" />
    <EmbeddedResource Remove="FiniteElementAnalysis\FiniteElements\Brick\**" />
    <EmbeddedResource Remove="FiniteElementAnalysis\FiniteElements\Plate\**" />
    <None Remove="FiniteElementAnalysis\FiniteElements\Brick\**" />
    <None Remove="FiniteElementAnalysis\FiniteElements\Plate\**" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(Configuration)' == 'Debug' Or '$(Configuration)' == 'Release' ">
    <PackageReference Include="DelaunayMesh" Version="2.0.0.3" />
    <PackageReference Include="GPCGeometry" Version="2.0.1.9" />
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)' == 'DebugLocalLibs' ">
    <Reference Include="DelaunayMesh">
      <HintPath>..\..\GPCGeometry\DelaunayMesh\bin\Debug\netstandard2.0\DelaunayMesh.dll</HintPath>
    </Reference>
    <Reference Include="GPCGeometry">
      <HintPath>..\..\GPCGeometry\GPCGeometry\bin\Debug\netstandard2.0\GPCGeometry.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GPCUtilities" Version="2.0.0.5" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Materials\Aluminium\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Condition="'$(Configuration)' == 'DebugLocalLibs'" Command="nuget.exe restore &quot;$(ProjectDir)..\..\GPCGeometry\GPCGeometry.sln&quot;&#xD;&#xA;call &quot;C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe&quot; &quot;$(ProjectDir)..\..\GPCGeometry\GPCGeometry.sln&quot; /p:Configuration=Debug /l:FileLogger,Microsoft.Build.Engine;logfile=BuildFromDependantProject.log" />
  </Target>

</Project>
