<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>    
  <RootNamespace>GPC.Model</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DelaunayMesh" Version="2.0.0" />
    <PackageReference Include="GPCGeometry" Version="2.0.0.3" />
    <PackageReference Include="GPCUtilities" Version="2.0.0.1" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="GPCGeometry">
      <HintPath>..\..\gpc-geometry\GPCGeometry\bin\Debug\netstandard2.0\GPCGeometry.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
