<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GMesh" Version="1.0.1.2" />
    <PackageReference Include="GPCGeometry" Version="2.0.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GPCModel\GPCModel.csproj" />
  </ItemGroup>

</Project>
