// Frozen v1 fingerprint vocabulary. Wire names are independent of CLR names.
// Change the CLR mapping deliberately; retain the wire name for a compatible refactor.
namespace GPC.Model.Core
{
    internal static partial class FingerprintContracts
    {
        private static void RegisterBuiltIns()
        {
            Register("GPC.Model.Structure.Members.PhysicalSurfaceDefinition", "GPC.Model.Structure.PhysicalSurfaceDefinition",
                Field("GPC.Model.Structure.Members.PhysicalSurfaceDefinition", "<Id>k__BackingField", "<Id>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalSurfaceDefinition", "<Name>k__BackingField", "<Name>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalSurfaceDefinition", "<Source>k__BackingField", "<Source>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalSurfaceDefinition", "_elements", "_elements", false),
                Field("GPC.Model.Structure.Members.PhysicalSurfaceDefinition", "_zones", "_zones", false));
            Register("GPC.Model.Structure.Members.SurfaceZoneDefinition", "GPC.Model.Structure.SurfaceZoneDefinition",
                Field("GPC.Model.Structure.Members.SurfaceZoneDefinition", "<Id>k__BackingField", "<Id>k__BackingField", false),
                Field("GPC.Model.Structure.Members.SurfaceZoneDefinition", "<Name>k__BackingField", "<Name>k__BackingField", false),
                Field("GPC.Model.Structure.Members.SurfaceZoneDefinition", "_elements", "_elements", false));
            Register("GPC.Model.Checking.Preparation.SurfaceSelection", "GPC.Model.Checking.SurfaceSelection",
                Field("GPC.Model.Checking.Preparation.SurfaceSelection", "<SurfaceId>k__BackingField", "<SurfaceId>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.SurfaceSelection", "<ZoneId>k__BackingField", "<ZoneId>k__BackingField", false));
            Register("GPC.Model.Attributes.BeamDofConnection", "GPC.Model.Attributes.BeamDofConnection",
                Field("GPC.Model.Attributes.BeamDofConnection", "<Kind>k__BackingField", "<Kind>k__BackingField", false),
                Field("GPC.Model.Attributes.BeamDofConnection", "<Value>k__BackingField", "<Value>k__BackingField", false));
            Register("GPC.Model.Geotechnics.Soil", "GPC.Model.Geotechnics.Soil",
                Field("GPC.Model.Geotechnics.Soil", "_cohesion", "_cohesion", false),
                Field("GPC.Model.Geotechnics.Soil", "_constrainedModulus", "_constrainedModulus", false),
                Field("GPC.Model.Geotechnics.Soil", "_frictionAngle", "_frictionAngle", false),
                Field("GPC.Model.Geotechnics.Soil", "_name", "_name", false),
                Field("GPC.Model.Geotechnics.Soil", "_poissonRatio", "_poissonRatio", false),
                Field("GPC.Model.Geotechnics.Soil", "_saturatedUnitWeight", "_saturatedUnitWeight", false),
                Field("GPC.Model.Geotechnics.Soil", "_source", "_source", false),
                Field("GPC.Model.Geotechnics.Soil", "_undrainedShearStrength", "_undrainedShearStrength", false),
                Field("GPC.Model.Geotechnics.Soil", "_unitWeight", "_unitWeight", false),
                Field("GPC.Model.Geotechnics.Soil", "_youngModulus", "_youngModulus", false));
            Register("GPC.Model.Geotechnics.SoilLayer", "GPC.Model.Geotechnics.SoilLayer",
                Field("GPC.Model.Geotechnics.SoilLayer", "_bottom", "_bottom", false),
                Field("GPC.Model.Geotechnics.SoilLayer", "_soil", "_soil", false),
                Field("GPC.Model.Geotechnics.SoilLayer", "_top", "_top", false));
            Register("GPC.Model.Geotechnics.SoilProfile", "GPC.Model.Geotechnics.SoilProfile",
                Field("GPC.Model.Geotechnics.SoilProfile", "_groundwater", "_groundwater", false),
                Field("GPC.Model.Geotechnics.SoilProfile", "_layers", "_layers", false),
                Field("GPC.Model.Geotechnics.SoilProfile", "_name", "_name", false),
                Field("GPC.Model.Geotechnics.SoilProfile", "_source", "_source", false),
                Field("GPC.Model.Geotechnics.SoilProfile", "_waterUnitWeight", "_waterUnitWeight", false));
            Register("GPC.Model.Materials.StressStrainTable", "GPC.Model.Materials.StressStrainTable",
                Field("GPC.Model.Materials.StressStrainTable", "_strains", "_strains", false),
                Field("GPC.Model.Materials.StressStrainTable", "_stresses", "_stresses", false));
            Register("GPC.Model.Analysis.AnalysisDataset", "GPC.Model.PostProcessing.AnalysisDataset",
                Field("GPC.Model.Analysis.AnalysisDataset", "<AnalysisId>k__BackingField", "<AnalysisId>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<AnalysisSnapshotId>k__BackingField", "<AnalysisSnapshotId>k__BackingField", true),
                Field("GPC.Model.Analysis.AnalysisDataset", "<Id>k__BackingField", "<Id>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<InputFingerprint>k__BackingField", "<InputFingerprint>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<IsSynthetic>k__BackingField", "<IsSynthetic>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<ModelRevision>k__BackingField", "<ModelRevision>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<NormalizedUnits>k__BackingField", "<NormalizedUnits>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<Program>k__BackingField", "<Program>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<Semantics>k__BackingField", "<Semantics>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<SolverVersion>k__BackingField", "<SolverVersion>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisDataset", "<SourceHashes>k__BackingField", "<SourceHashes>k__BackingField", false));
            Register("GPC.Model.Analysis.AnalysisSnapshot", "GPC.Model.PostProcessing.AnalysisSnapshot",
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<AssumptionReference>k__BackingField", "<AssumptionReference>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<Id>k__BackingField", "<Id>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<InputFingerprint>k__BackingField", "<InputFingerprint>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<ModelGuid>k__BackingField", "<ModelGuid>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<PrestressFingerprint>k__BackingField", "<PrestressFingerprint>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<ReinforcementFingerprint>k__BackingField", "<ReinforcementFingerprint>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<ReinforcementRole>k__BackingField", "<ReinforcementRole>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "<SourceFingerprint>k__BackingField", "<SourceFingerprint>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "_contentHash", "_contentHash", false),
                Field("GPC.Model.Analysis.AnalysisSnapshot", "_model", "_model", false));
            Register("GPC.Model.Analysis.AnalysisSource", "GPC.Model.PostProcessing.AnalysisSource",
                Field("GPC.Model.Analysis.AnalysisSource", "<AnalysisId>k__BackingField", "<AnalysisId>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSource", "<GeometryHash>k__BackingField", "<GeometryHash>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSource", "<ModelRevision>k__BackingField", "<ModelRevision>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSource", "<Program>k__BackingField", "<Program>k__BackingField", false),
                Field("GPC.Model.Analysis.AnalysisSource", "<SolverVersion>k__BackingField", "<SolverVersion>k__BackingField", false));
            Register("GPC.Model.Analysis.BeamAnalysisProfile", "GPC.Model.PostProcessing.BeamAnalysisProfile",
                Field("GPC.Model.Analysis.BeamAnalysisProfile", "<Interpolation>k__BackingField", "<Interpolation>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisProfile", "<Modifiers>k__BackingField", "<Modifiers>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisProfile", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisProfile", "<StationDomain>k__BackingField", "<StationDomain>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisProfile", "<Stations>k__BackingField", "<Stations>k__BackingField", false));
            Register("GPC.Model.Analysis.BeamAnalysisStation", "GPC.Model.PostProcessing.BeamAnalysisStation",
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<EA>k__BackingField", "<EA>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<EI1>k__BackingField", "<EI1>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<EI2>k__BackingField", "<EI2>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<GA1>k__BackingField", "<GA1>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<GA2>k__BackingField", "<GA2>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<GJ>k__BackingField", "<GJ>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<MassPerLength>k__BackingField", "<MassPerLength>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamAnalysisStation", "<Station>k__BackingField", "<Station>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.BeamAssignments", "GPC.Model.PostProcessing.BeamAssignments",
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<ActionsAtSectionCentroidConfirmed>k__BackingField", "<ActionsAtSectionCentroidConfirmed>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<AnalysisProfile>k__BackingField", "<AnalysisProfile>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<Formulation>k__BackingField", "<Formulation>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<Loads>k__BackingField", "<Loads>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<LogicalMember>k__BackingField", "<LogicalMember>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<OffsetAxes>k__BackingField", "<OffsetAxes>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<OffsetI>k__BackingField", "<OffsetI>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<OffsetJ>k__BackingField", "<OffsetJ>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<OrientationNodeId>k__BackingField", "<OrientationNodeId>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<OtherAssignments>k__BackingField", "<OtherAssignments>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<RigidLengthI>k__BackingField", "<RigidLengthI>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<RigidLengthJ>k__BackingField", "<RigidLengthJ>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<SectionAxes>k__BackingField", "<SectionAxes>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<SectionCentroidOffset>k__BackingField", "<SectionCentroidOffset>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<SectionGeometryAxes>k__BackingField", "<SectionGeometryAxes>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<Sections>k__BackingField", "<Sections>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamAssignments", "<StationDomain>k__BackingField", "<StationDomain>k__BackingField", false));
            Register("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "GPC.Model.PostProcessing.BeamCheckPlanRequest",
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<CoveragePolicy>k__BackingField", "<CoveragePolicy>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<Elements>k__BackingField", "<Elements>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<Locations>k__BackingField", "<Locations>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<MemberChecks>k__BackingField", "<MemberChecks>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<MemberIds>k__BackingField", "<MemberIds>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<Results>k__BackingField", "<Results>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<SectionChecks>k__BackingField", "<SectionChecks>k__BackingField", true),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<SectionMechanisms>k__BackingField", "<SectionMechanisms>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.BeamCheckPlanRequest", "<Settings>k__BackingField", "<Settings>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.BeamForceSnapshot", "GPC.Model.PostProcessing.BeamForceSnapshot",
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "<M1>k__BackingField", "<M1>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "<M2>k__BackingField", "<M2>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "<N>k__BackingField", "<N>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "<T>k__BackingField", "<T>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "<V1>k__BackingField", "<V1>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "<V2>k__BackingField", "<V2>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.BeamForceSnapshot", "_axes", "_axes", false));
            Register("GPC.Model.Loads.Assignments.BeamLoadAssignment", "GPC.Model.PostProcessing.BeamLoadAssignment",
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<Concentrated>k__BackingField", "<Concentrated>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<Eccentricity>k__BackingField", "<Eccentricity>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<EccentricityCoordinateSystem>k__BackingField", "<EccentricityCoordinateSystem>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<End>k__BackingField", "<End>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<EndIntensity>k__BackingField", "<EndIntensity>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<IsEquivalentNodalRepresentation>k__BackingField", "<IsEquivalentNodalRepresentation>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<LengthConvention>k__BackingField", "<LengthConvention>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<OriginalAssignmentId>k__BackingField", "<OriginalAssignmentId>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<ProjectionPlaneNormal>k__BackingField", "<ProjectionPlaneNormal>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<Start>k__BackingField", "<Start>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<StartIntensity>k__BackingField", "<StartIntensity>k__BackingField", false),
                Field("GPC.Model.Loads.Assignments.BeamLoadAssignment", "<StationDomain>k__BackingField", "<StationDomain>k__BackingField", false));
            Register("GPC.Model.Structure.Members.BeamMemberPart", "GPC.Model.PostProcessing.BeamMemberPart",
                Field("GPC.Model.Structure.Members.BeamMemberPart", "<AlongIJ>k__BackingField", "<AlongIJ>k__BackingField", false),
                Field("GPC.Model.Structure.Members.BeamMemberPart", "<BeamId>k__BackingField", "<BeamId>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.BeamSectionAssignment", "GPC.Model.PostProcessing.BeamSectionAssignment",
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "<End>k__BackingField", "<End>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "<EndSection>k__BackingField", "<EndSection>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "<Law>k__BackingField", "<Law>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "<Section>k__BackingField", "<Section>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "<Start>k__BackingField", "<Start>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "<Stations>k__BackingField", "<Stations>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "_endProperty", "_endProperty", true),
                Field("GPC.Model.Structure.Assignments.BeamSectionAssignment", "_property", "_property", true));
            Register("GPC.Model.Structure.Assignments.BeamSectionStation", "GPC.Model.PostProcessing.BeamSectionStation",
                Field("GPC.Model.Structure.Assignments.BeamSectionStation", "<Section>k__BackingField", "<Section>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionStation", "<Side>k__BackingField", "<Side>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionStation", "<Station>k__BackingField", "<Station>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.BeamSectionStation", "_property", "_property", true));
            Register("GPC.Model.Analysis.BeamStiffnessModifiers", "GPC.Model.PostProcessing.BeamStiffnessModifiers",
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Axial>k__BackingField", "<Axial>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Bending1>k__BackingField", "<Bending1>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Bending2>k__BackingField", "<Bending2>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Mass>k__BackingField", "<Mass>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Shear1>k__BackingField", "<Shear1>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Shear2>k__BackingField", "<Shear2>k__BackingField", false),
                Field("GPC.Model.Analysis.BeamStiffnessModifiers", "<Torsion>k__BackingField", "<Torsion>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckCalculationValue", "GPC.Model.PostProcessing.CheckCalculationValue",
                Field("GPC.Model.Checking.Reports.CheckCalculationValue", "<Expression>k__BackingField", "<Expression>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckCalculationValue", "<Key>k__BackingField", "<Key>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckCalculationValue", "<Unit>k__BackingField", "<Unit>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckCalculationValue", "<Value>k__BackingField", "<Value>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckConvergence", "GPC.Model.PostProcessing.CheckConvergence",
                Field("GPC.Model.Checking.Reports.CheckConvergence", "<Converged>k__BackingField", "<Converged>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckConvergence", "<Criterion>k__BackingField", "<Criterion>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckConvergence", "<Iterations>k__BackingField", "<Iterations>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckConvergence", "<Residual>k__BackingField", "<Residual>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckConvergence", "<Tolerance>k__BackingField", "<Tolerance>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckDetails", "GPC.Model.PostProcessing.CheckDetails",
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Checking.Reports.CheckInputSnapshot", "GPC.Model.PostProcessing.CheckInputSnapshot",
                Field("GPC.Model.Checking.Reports.CheckInputSnapshot", "<BeamForces>k__BackingField", "<BeamForces>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckInputSnapshot", "<ForcesFingerprint>k__BackingField", "<ForcesFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckInputSnapshot", "<SampleFingerprint>k__BackingField", "<SampleFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckInputSnapshot", "<SectionFingerprint>k__BackingField", "<SectionFingerprint>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckMetric", "GPC.Model.PostProcessing.CheckMetric",
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Capacity>k__BackingField", "<Capacity>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Demand>k__BackingField", "<Demand>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Key>k__BackingField", "<Key>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Passed>k__BackingField", "<Passed>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Reference>k__BackingField", "<Reference>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Unit>k__BackingField", "<Unit>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckMetric", "<Utilization>k__BackingField", "<Utilization>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckPointValue", "GPC.Model.PostProcessing.CheckPointValue",
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<Frame>k__BackingField", "<Frame>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<Key>k__BackingField", "<Key>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<Unit>k__BackingField", "<Unit>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<Value>k__BackingField", "<Value>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<X>k__BackingField", "<X>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<Y>k__BackingField", "<Y>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckPointValue", "<Z>k__BackingField", "<Z>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckReport", "GPC.Model.PostProcessing.CheckReport",
                Field("GPC.Model.Checking.Reports.CheckReport", "<BeamScope>k__BackingField", "<BeamScope>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckReport", "<Job>k__BackingField", "<Job>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckReport", "<Required>k__BackingField", "<Required>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckReport", "<Results>k__BackingField", "<Results>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckReport", "<Scope>k__BackingField", "<Scope>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckReport", "<ScopeFingerprint>k__BackingField", "<ScopeFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckReport", "_resultSlotsFingerprint", "_resultSlotsFingerprint", false));
            Register("GPC.Model.Checking.Contracts.CheckResult", "GPC.Model.PostProcessing.CheckResult",
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Applicability>k__BackingField", "<Applicability>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ApplicabilityReason>k__BackingField", "<ApplicabilityReason>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Case>k__BackingField", "<Case>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Check>k__BackingField", "<Check>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ConcomitantStateId>k__BackingField", "<ConcomitantStateId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Coverage>k__BackingField", "<Coverage>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<CoverageAssessment>k__BackingField", "<CoverageAssessment>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Data>k__BackingField", "<Data>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Dataset>k__BackingField", "<Dataset>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Details>k__BackingField", "<Details>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Diagnostics>k__BackingField", "<Diagnostics>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ElementId>k__BackingField", "<ElementId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<EngineConfiguration>k__BackingField", "<EngineConfiguration>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<EngineVersion>k__BackingField", "<EngineVersion>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<EvidenceFingerprint>k__BackingField", "<EvidenceFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Execution>k__BackingField", "<Execution>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Face>k__BackingField", "<Face>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Family>k__BackingField", "<Family>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<GroupNames>k__BackingField", "<GroupNames>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Input>k__BackingField", "<Input>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Job>k__BackingField", "<Job>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Layer>k__BackingField", "<Layer>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Mechanism>k__BackingField", "<Mechanism>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<MemberInput>k__BackingField", "<MemberInput>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<MemberLocation>k__BackingField", "<MemberLocation>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Mode>k__BackingField", "<Mode>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<MovingLoadPosition>k__BackingField", "<MovingLoadPosition>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Outcome>k__BackingField", "<Outcome>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Phase>k__BackingField", "<Phase>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<PlanItemId>k__BackingField", "<PlanItemId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Provenance>k__BackingField", "<Provenance>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<SampleRevision>k__BackingField", "<SampleRevision>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<SchemaVersion>k__BackingField", "<SchemaVersion>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Scope>k__BackingField", "<Scope>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Settings>k__BackingField", "<Settings>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ShellCoordinateKind>k__BackingField", "<ShellCoordinateKind>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ShellInput>k__BackingField", "<ShellInput>k__BackingField", true),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ShellCheck>k__BackingField", "<ShellCheck>k__BackingField", true),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ShellPoint>k__BackingField", "<ShellPoint>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<ShellPointKind>k__BackingField", "<ShellPointKind>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Side>k__BackingField", "<Side>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Source>k__BackingField", "<Source>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Standard>k__BackingField", "<Standard>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Station>k__BackingField", "<Station>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Step>k__BackingField", "<Step>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Target>k__BackingField", "<Target>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<Utilization>k__BackingField", "<Utilization>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckResult", "<VerificationRevision>k__BackingField", "<VerificationRevision>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.CheckStandardContext", "GPC.Model.PostProcessing.CheckStandardContext",
                Field("GPC.Model.Checking.Reports.CheckStandardContext", "<Code>k__BackingField", "<Code>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckStandardContext", "<Edition>k__BackingField", "<Edition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckStandardContext", "<Implementation>k__BackingField", "<Implementation>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckStandardContext", "<NationalAnnex>k__BackingField", "<NationalAnnex>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckStandardContext", "<Parameters>k__BackingField", "<Parameters>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckStandardContext", "<Reference>k__BackingField", "<Reference>k__BackingField", false));
            Register("GPC.Model.Checking.Contracts.CheckTargetReference", "GPC.Model.PostProcessing.CheckTargetReference",
                Field("GPC.Model.Checking.Contracts.CheckTargetReference", "<BeamId>k__BackingField", "<BeamId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckTargetReference", "<ElementId>k__BackingField", "<ElementId>k__BackingField", true),
                Field("GPC.Model.Checking.Contracts.CheckTargetReference", "<Family>k__BackingField", "<Family>k__BackingField", true),
                Field("GPC.Model.Checking.Contracts.CheckTargetReference", "<Kind>k__BackingField", "<Kind>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CheckTargetReference", "<MemberId>k__BackingField", "<MemberId>k__BackingField", false));
            Register("GPC.Model.Checking.Contracts.CoverageAssessment", "GPC.Model.PostProcessing.CoverageAssessment",
                Field("GPC.Model.Checking.Contracts.CoverageAssessment", "<AvailableLocations>k__BackingField", "<AvailableLocations>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CoverageAssessment", "<Policy>k__BackingField", "<Policy>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.CoverageAssessment", "<RequiredLocations>k__BackingField", "<RequiredLocations>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.DetailingCheckDetails", "GPC.Model.PostProcessing.DetailingCheckDetails",
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Checking.Preparation.ElementKey", "GPC.Model.PostProcessing.ElementKey",
                Field("GPC.Model.Checking.Preparation.ElementKey", "<Family>k__BackingField", "<Family>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.ElementKey", "<Id>k__BackingField", "<Id>k__BackingField", false));
            Register("GPC.Model.Checking.Preparation.ElementSelection", "GPC.Model.PostProcessing.ElementSelection",
                Field("GPC.Model.Checking.Preparation.ElementSelection", "<Surfaces>k__BackingField", "<Surfaces>k__BackingField", true),
                Field("GPC.Model.Checking.Preparation.ElementSelection", "<Elements>k__BackingField", "<Elements>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.ElementSelection", "<Families>k__BackingField", "<Families>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.ElementSelection", "<Groups>k__BackingField", "<Groups>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.ElementSelection", "<IncludeDescendants>k__BackingField", "<IncludeDescendants>k__BackingField", false));
            Register("GPC.Model.Checking.Contracts.MemberCheckSpecification", "GPC.Model.PostProcessing.MemberCheckSpecification",
                Field("GPC.Model.Checking.Contracts.MemberCheckSpecification", "<Context>k__BackingField", "<Context>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberCheckSpecification", "<End>k__BackingField", "<End>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberCheckSpecification", "<Mechanism>k__BackingField", "<Mechanism>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberCheckSpecification", "<MemberId>k__BackingField", "<MemberId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberCheckSpecification", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberCheckSpecification", "<Start>k__BackingField", "<Start>k__BackingField", false));
            Register("GPC.Model.Structure.Members.MemberDesignContext", "GPC.Model.PostProcessing.MemberDesignContext",
                Field("GPC.Model.Structure.Members.MemberDesignContext", "<Assumptions>k__BackingField", "<Assumptions>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberDesignContext", "<EffectiveLength1>k__BackingField", "<EffectiveLength1>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberDesignContext", "<EffectiveLength2>k__BackingField", "<EffectiveLength2>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberDesignContext", "<GlobalStateConfirmed>k__BackingField", "<GlobalStateConfirmed>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberDesignContext", "<LateralTorsionalLength>k__BackingField", "<LateralTorsionalLength>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberDesignContext", "<LengthSource>k__BackingField", "<LengthSource>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberDesignContext", "_restraints", "_restraints", false));
            Register("GPC.Model.Checking.Contracts.MemberInputSnapshot", "GPC.Model.PostProcessing.MemberInputSnapshot",
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "<Context>k__BackingField", "<Context>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "<Definition>k__BackingField", "<Definition>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "<DeformableLength>k__BackingField", "<DeformableLength>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "<Length>k__BackingField", "<Length>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "<SpanEnd>k__BackingField", "<SpanEnd>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "<SpanStart>k__BackingField", "<SpanStart>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "_axes", "_axes", false),
                Field("GPC.Model.Checking.Contracts.MemberInputSnapshot", "_samples", "_samples", false));
            Register("GPC.Model.Structure.Members.MemberLocation", "GPC.Model.PostProcessing.MemberLocation",
                Field("GPC.Model.Structure.Members.MemberLocation", "<BeamId>k__BackingField", "<BeamId>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberLocation", "<Distance>k__BackingField", "<Distance>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberLocation", "<MemberId>k__BackingField", "<MemberId>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberLocation", "<Side>k__BackingField", "<Side>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberLocation", "<Station>k__BackingField", "<Station>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberLocation", "<StationDomain>k__BackingField", "<StationDomain>k__BackingField", false));
            Register("GPC.Model.Structure.Members.MemberRestraint", "GPC.Model.PostProcessing.MemberRestraint",
                Field("GPC.Model.Structure.Members.MemberRestraint", "<Distance>k__BackingField", "<Distance>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberRestraint", "<Phase>k__BackingField", "<Phase>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberRestraint", "<Source>k__BackingField", "<Source>k__BackingField", false),
                Field("GPC.Model.Structure.Members.MemberRestraint", "_axes", "_axes", false),
                Field("GPC.Model.Structure.Members.MemberRestraint", "_restrained", "_restrained", false));
            Register("GPC.Model.Checking.Contracts.MemberSampleSnapshot", "GPC.Model.PostProcessing.MemberSampleSnapshot",
                Field("GPC.Model.Checking.Contracts.MemberSampleSnapshot", "<Input>k__BackingField", "<Input>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberSampleSnapshot", "<Location>k__BackingField", "<Location>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.MemberSampleSnapshot", "_state", "_state", false));
            Register("GPC.Model.Core.Diagnostics.ModelDiagnostic", "GPC.Model.PostProcessing.ModelDiagnostic",
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Case>k__BackingField", "<Case>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Code>k__BackingField", "<Code>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Dataset>k__BackingField", "<Dataset>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<ElementId>k__BackingField", "<ElementId>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Family>k__BackingField", "<Family>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Message>k__BackingField", "<Message>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Record>k__BackingField", "<Record>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Severity>k__BackingField", "<Severity>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<Station>k__BackingField", "<Station>k__BackingField", false),
                Field("GPC.Model.Core.Diagnostics.ModelDiagnostic", "<SuggestedAction>k__BackingField", "<SuggestedAction>k__BackingField", false));
            Register("GPC.Model.Checking.Preparation.NativeMethodDetails", "GPC.Model.PostProcessing.NativeMethodDetails",
                Field("GPC.Model.Checking.Preparation.NativeMethodDetails", "<NativeInputFingerprint>k__BackingField", "<NativeInputFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.NativeMethodDetails", "<ScopeDescription>k__BackingField", "<ScopeDescription>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.NativeMethodDetails", "_warnings", "_warnings", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Structure.Assignments.NodalLink", "GPC.Model.PostProcessing.NodalLink",
                Field("GPC.Model.Structure.Assignments.NodalLink", "<KinematicCoefficients>k__BackingField", "<KinematicCoefficients>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalLink", "<LeverArm>k__BackingField", "<LeverArm>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalLink", "<OtherNodeId>k__BackingField", "<OtherNodeId>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalLink", "<RightHandSide>k__BackingField", "<RightHandSide>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalLink", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalLink", "<Spring>k__BackingField", "<Spring>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalLink", "<UnsupportedLaw>k__BackingField", "<UnsupportedLaw>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.NodalMass", "GPC.Model.PostProcessing.NodalMass",
                Field("GPC.Model.Structure.Assignments.NodalMass", "<Axes>k__BackingField", "<Axes>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalMass", "<IncludedInSourceTotal>k__BackingField", "<IncludedInSourceTotal>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalMass", "<Matrix6x6RowMajor>k__BackingField", "<Matrix6x6RowMajor>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodalMass", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.NodeAssignments", "GPC.Model.PostProcessing.NodeAssignments",
                Field("GPC.Model.Structure.Assignments.NodeAssignments", "<Active>k__BackingField", "<Active>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodeAssignments", "<Dofs>k__BackingField", "<Dofs>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodeAssignments", "<GroundSprings>k__BackingField", "<GroundSprings>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodeAssignments", "<Links>k__BackingField", "<Links>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodeAssignments", "<Mass>k__BackingField", "<Mass>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.NodeAssignments", "<Restrains>k__BackingField", "<Restrains>k__BackingField", false));
            Register("GPC.Model.Results.State.OriginalResultData", "GPC.Model.PostProcessing.OriginalResultData",
                Field("GPC.Model.Results.State.OriginalResultData", "<AngleToRad>k__BackingField", "<AngleToRad>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<Axes>k__BackingField", "<Axes>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<ComponentOrder>k__BackingField", "<ComponentOrder>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<Convention>k__BackingField", "<Convention>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<DenominatorLengthToMm>k__BackingField", "<DenominatorLengthToMm>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<ForceToN>k__BackingField", "<ForceToN>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<LengthToMm>k__BackingField", "<LengthToMm>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<MomentToNmm>k__BackingField", "<MomentToNmm>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<ReaderVersion>k__BackingField", "<ReaderVersion>k__BackingField", false),
                Field("GPC.Model.Results.State.OriginalResultData", "<Values>k__BackingField", "<Values>k__BackingField", false));
            Register("GPC.Model.Structure.Members.PhysicalMemberDefinition", "GPC.Model.PostProcessing.PhysicalMemberDefinition",
                Field("GPC.Model.Structure.Members.PhysicalMemberDefinition", "<Id>k__BackingField", "<Id>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalMemberDefinition", "<Name>k__BackingField", "<Name>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalMemberDefinition", "<Source>k__BackingField", "<Source>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalMemberDefinition", "<StationDomain>k__BackingField", "<StationDomain>k__BackingField", false),
                Field("GPC.Model.Structure.Members.PhysicalMemberDefinition", "_parts", "_parts", false));
            Register("GPC.Model.Checking.Preparation.PreparationRequest", "GPC.Model.PostProcessing.PreparationRequest",
                Field("GPC.Model.Checking.Preparation.PreparationRequest", "<Mechanisms>k__BackingField", "<Mechanisms>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.PreparationRequest", "<Results>k__BackingField", "<Results>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.PreparationRequest", "<Selection>k__BackingField", "<Selection>k__BackingField", false),
                Field("GPC.Model.Checking.Preparation.PreparationRequest", "<Settings>k__BackingField", "<Settings>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.PreservedAssignment", "GPC.Model.PostProcessing.PreservedAssignment",
                Field("GPC.Model.Structure.Assignments.PreservedAssignment", "<Kind>k__BackingField", "<Kind>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.PreservedAssignment", "<RawData>k__BackingField", "<RawData>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.PreservedAssignment", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.PreservedAssignment", "<UnitsAndAxes>k__BackingField", "<UnitsAndAxes>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.PreservedAssignment", "<UnsupportedReason>k__BackingField", "<UnsupportedReason>k__BackingField", false));
            Register("GPC.Model.Checking.Contracts.RequiredBeamLocation", "GPC.Model.PostProcessing.RequiredBeamLocation",
                Field("GPC.Model.Checking.Contracts.RequiredBeamLocation", "<BeamId>k__BackingField", "<BeamId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.RequiredBeamLocation", "<Distance>k__BackingField", "<Distance>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.RequiredBeamLocation", "<MemberId>k__BackingField", "<MemberId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.RequiredBeamLocation", "<Side>k__BackingField", "<Side>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.RequiredBeamLocation", "<Station>k__BackingField", "<Station>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.RequiredBeamLocation", "<StationDomain>k__BackingField", "<StationDomain>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.RestrainAssignment", "GPC.Model.PostProcessing.RestrainAssignment",
                Field("GPC.Model.Structure.Assignments.RestrainAssignment", "<Case>k__BackingField", "<Case>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.RestrainAssignment", "<Phase>k__BackingField", "<Phase>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.RestrainAssignment", "<Restrain>k__BackingField", "<Restrain>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.RestrainAssignment", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false));
            Register("GPC.Model.Results.Queries.ResultSelection", "GPC.Model.PostProcessing.ResultSelection",
                Field("GPC.Model.Results.Queries.ResultSelection", "<Case>k__BackingField", "<Case>k__BackingField", false),
                Field("GPC.Model.Results.Queries.ResultSelection", "<Category>k__BackingField", "<Category>k__BackingField", true),
                Field("GPC.Model.Results.Queries.ResultSelection", "<ConcomitantState>k__BackingField", "<ConcomitantState>k__BackingField", false),
                Field("GPC.Model.Results.Queries.ResultSelection", "<Dataset>k__BackingField", "<Dataset>k__BackingField", false),
                Field("GPC.Model.Results.Queries.ResultSelection", "<Mode>k__BackingField", "<Mode>k__BackingField", false),
                Field("GPC.Model.Results.Queries.ResultSelection", "<MovingLoadPosition>k__BackingField", "<MovingLoadPosition>k__BackingField", false),
                Field("GPC.Model.Results.Queries.ResultSelection", "<Phase>k__BackingField", "<Phase>k__BackingField", false),
                Field("GPC.Model.Results.Queries.ResultSelection", "<Step>k__BackingField", "<Step>k__BackingField", false));
            Register("GPC.Model.Results.State.ResultState", "GPC.Model.PostProcessing.ResultState",
                Field("GPC.Model.Results.State.ResultState", "<Components>k__BackingField", "<Components>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<ConcomitantStateId>k__BackingField", "<ConcomitantStateId>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Coverage>k__BackingField", "<Coverage>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<DatasetId>k__BackingField", "<DatasetId>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<DerivedFrom>k__BackingField", "<DerivedFrom>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<DerivedSourceFingerprint>k__BackingField", "<DerivedSourceFingerprint>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<HistoryId>k__BackingField", "<HistoryId>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<IncrementIndex>k__BackingField", "<IncrementIndex>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<IncrementsStartAtZero>k__BackingField", "<IncrementsStartAtZero>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<InputFingerprint>k__BackingField", "<InputFingerprint>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<IsCombined>k__BackingField", "<IsCombined>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<IsCumulative>k__BackingField", "<IsCumulative>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<IsSynthetic>k__BackingField", "<IsSynthetic>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Mode>k__BackingField", "<Mode>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<ModelRevision>k__BackingField", "<ModelRevision>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<MovingLoadPosition>k__BackingField", "<MovingLoadPosition>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Normalization>k__BackingField", "<Normalization>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Original>k__BackingField", "<Original>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Phase>k__BackingField", "<Phase>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Semantics>k__BackingField", "<Semantics>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<SourceHash>k__BackingField", "<SourceHash>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Step>k__BackingField", "<Step>k__BackingField", false),
                Field("GPC.Model.Results.State.ResultState", "<Transformation>k__BackingField", "<Transformation>k__BackingField", false));
            Register("GPC.Model.Checking.Contracts.SectionCheckSpecification", "GPC.Model.PostProcessing.SectionCheckSpecification",
                Field("GPC.Model.Checking.Contracts.SectionCheckSpecification", "<Category>k__BackingField", "<Category>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.SectionCheckSpecification", "<Criterion>k__BackingField", "<Criterion>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.SectionCheckSpecification", "<Direction>k__BackingField", "<Direction>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.SectionCheckSpecification", "<Mechanism>k__BackingField", "<Mechanism>k__BackingField", false));
            Register("GPC.Model.Checking.Reports.SectionResistanceDetails", "GPC.Model.PostProcessing.SectionResistanceDetails",
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<ChiX>k__BackingField", "<ChiX>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<ChiY>k__BackingField", "<ChiY>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<Demand>k__BackingField", "<Demand>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<FailureMode>k__BackingField", "<FailureMode>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<M1Rd>k__BackingField", "<M1Rd>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<M2Rd>k__BackingField", "<M2Rd>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<NRd>k__BackingField", "<NRd>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<StrainAtReference>k__BackingField", "<StrainAtReference>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<StrainReferenceX>k__BackingField", "<StrainReferenceX>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.SectionResistanceDetails", "<StrainReferenceY>k__BackingField", "<StrainReferenceY>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Checking.Reports.ServiceabilityCheckDetails", "GPC.Model.PostProcessing.ServiceabilityCheckDetails",
                Field("GPC.Model.Checking.Reports.ServiceabilityCheckDetails", "<CombinationCategory>k__BackingField", "<CombinationCategory>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Checking.Reports.ShearCheckDetails", "GPC.Model.PostProcessing.ShearCheckDetails",
                Field("GPC.Model.Checking.Reports.ShearCheckDetails", "<CotTheta>k__BackingField", "<CotTheta>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.ShearCheckDetails", "<Direction>k__BackingField", "<Direction>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Structure.Assignments.ShellAssignments", "GPC.Model.PostProcessing.ShellAssignments",
                Field("GPC.Model.Structure.Assignments.ShellAssignments", "<LayerAxes>k__BackingField", "<LayerAxes>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellAssignments", "<Layers>k__BackingField", "<Layers>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellAssignments", "<Offset>k__BackingField", "<Offset>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellAssignments", "<PhysicalThickness>k__BackingField", "<PhysicalThickness>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellAssignments", "<ReinforcementZone>k__BackingField", "<ReinforcementZone>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.ShellRebarLayer", "GPC.Model.PostProcessing.ShellRebarLayer",
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<AxisPositionThroughThickness>k__BackingField", "<AxisPositionThroughThickness>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<Diameter>k__BackingField", "<Diameter>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<DirectionRadians>k__BackingField", "<DirectionRadians>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<Order>k__BackingField", "<Order>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<PhysicalFace>k__BackingField", "<PhysicalFace>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<Pitch>k__BackingField", "<Pitch>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.ShellRebarLayer", "<Steel>k__BackingField", "<Steel>k__BackingField", false));
            Register("GPC.Model.Core.Identity.SourceIdentity", "GPC.Model.PostProcessing.SourceIdentity",
                Field("GPC.Model.Core.Identity.SourceIdentity", "<Family>k__BackingField", "<Family>k__BackingField", false),
                Field("GPC.Model.Core.Identity.SourceIdentity", "<ModelRevision>k__BackingField", "<ModelRevision>k__BackingField", false),
                Field("GPC.Model.Core.Identity.SourceIdentity", "<OriginalId>k__BackingField", "<OriginalId>k__BackingField", false),
                Field("GPC.Model.Core.Identity.SourceIdentity", "<Program>k__BackingField", "<Program>k__BackingField", false));
            Register("GPC.Model.Structure.Assignments.SpringMatrix", "GPC.Model.PostProcessing.SpringMatrix",
                Field("GPC.Model.Structure.Assignments.SpringMatrix", "<CoordinateSystem>k__BackingField", "<CoordinateSystem>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.SpringMatrix", "<Kind>k__BackingField", "<Kind>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.SpringMatrix", "<SourceRecord>k__BackingField", "<SourceRecord>k__BackingField", false),
                Field("GPC.Model.Structure.Assignments.SpringMatrix", "_values", "_values", false));
            Register("GPC.Model.Checking.Reports.TorsionCheckDetails", "GPC.Model.PostProcessing.TorsionCheckDetails",
                Field("GPC.Model.Checking.Reports.TorsionCheckDetails", "<RequiredLongitudinalArea>k__BackingField", "<RequiredLongitudinalArea>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<Convergence>k__BackingField", "<Convergence>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<MethodId>k__BackingField", "<MethodId>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "<UtilizationDefinition>k__BackingField", "<UtilizationDefinition>k__BackingField", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_metrics", "_metrics", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_points", "_points", false),
                Field("GPC.Model.Checking.Reports.CheckDetails", "_trace", "_trace", false));
            Register("GPC.Model.Checking.Contracts.VerificationProvenance", "GPC.Model.PostProcessing.VerificationProvenance",
                Field("GPC.Model.Checking.Contracts.VerificationProvenance", "<AnalysisFingerprint>k__BackingField", "<AnalysisFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.VerificationProvenance", "<AnalysisSnapshotId>k__BackingField", "<AnalysisSnapshotId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.VerificationProvenance", "<DesignFingerprint>k__BackingField", "<DesignFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.VerificationProvenance", "<ScenarioFingerprint>k__BackingField", "<ScenarioFingerprint>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.VerificationProvenance", "<ScenarioId>k__BackingField", "<ScenarioId>k__BackingField", false),
                Field("GPC.Model.Checking.Contracts.VerificationProvenance", "_datasets", "_datasets", false));
            Register("GPC.Model.Checking.Scenarios.VerificationScenario", "GPC.Model.PostProcessing.VerificationScenario",
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "_plateSections", "_plateSections", true),
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "<AnalysisId>k__BackingField", "<AnalysisId>k__BackingField", false),
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "<Id>k__BackingField", "<Id>k__BackingField", false),
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "<Name>k__BackingField", "<Name>k__BackingField", false),
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "_beams", "_beams", false),
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "_sections", "_sections", false),
                Field("GPC.Model.Checking.Scenarios.VerificationScenario", "_shells", "_shells", false));
            Register("GPC.Model.Sections.Concrete.ConcreteCrackData", "GPC.Model.Sections.Concrete.ConcreteCrackData",
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_concentricRings", "_concentricRings", false),
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_cover", "_cover", false),
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_exposure", "_exposure", false),
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_maximumBarSpacing", "_maximumBarSpacing", false),
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_ribbed", "_ribbed", false),
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_sensitive", "_sensitive", false),
                Field("GPC.Model.Sections.Concrete.ConcreteCrackData", "_source", "_source", false));
            Register("GPC.Model.Sections.Concrete.ConcreteDetailingData", "GPC.Model.Sections.Concrete.ConcreteDetailingData",
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_aggregate", "_aggregate", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_bottomWidth", "_bottomWidth", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_compressionBarsRestrained", "_compressionBarsRestrained", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_coverDeviation", "_coverDeviation", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_endZonesConfirmed", "_endZonesConfirmed", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_lapZone", "_lapZone", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_minimumDurabilityCover", "_minimumDurabilityCover", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_nominalCover", "_nominalCover", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_source", "_source", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_topWidth", "_topWidth", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDetailingData", "_webWidth", "_webWidth", false));
            Register("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "GPC.Model.Sections.Concrete.ConcreteDurabilityData",
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_abrasion", "_abrasion", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_designLife", "_designLife", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_exposures", "_exposures", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_ground", "_ground", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_ntcQualityReduction", "_ntcQualityReduction", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_pertinentCmin", "_pertinentCmin", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_roughSurface", "_roughSurface", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_source", "_source", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_specialQualityControl", "_specialQualityControl", false),
                Field("GPC.Model.Sections.Concrete.ConcreteDurabilityData", "_strengthReduction", "_strengthReduction", false));
            Register("GPC.Model.Sections.Concrete.ConcreteShearData", "GPC.Model.Sections.Concrete.ConcreteShearData",
                Field("GPC.Model.Sections.Concrete.ConcreteShearData", "_aggregateSize", "_aggregateSize", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearData", "_axis1", "_axis1", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearData", "_axis2", "_axis2", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearData", "_reinforcement", "_reinforcement", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearData", "_source", "_source", false));
            Register("GPC.Model.Sections.Concrete.ConcreteShearDirection", "GPC.Model.Sections.Concrete.ConcreteShearDirection",
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_anchored", "_anchored", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_axialEccentricity", "_axialEccentricity", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_effectiveDepth", "_effectiveDepth", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_legs", "_legs", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_leverFactor", "_leverFactor", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_longitudinalCover", "_longitudinalCover", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_tensionArea", "_tensionArea", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearDirection", "_webWidth", "_webWidth", false));
            Register("GPC.Model.Sections.Concrete.ConcreteShearReinforcement", "GPC.Model.Sections.Concrete.ConcreteShearReinforcement",
                Field("GPC.Model.Sections.Concrete.ConcreteShearReinforcement", "_angle", "_angle", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearReinforcement", "_diameter", "_diameter", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearReinforcement", "_material", "_material", false),
                Field("GPC.Model.Sections.Concrete.ConcreteShearReinforcement", "_spacing", "_spacing", false));
            Register("GPC.Model.Sections.Concrete.ConcreteTorsionData", "GPC.Model.Sections.Concrete.ConcreteTorsionData",
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_closedLinksConfirmed", "_closedLinksConfirmed", false),
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_enclosedArea", "_enclosedArea", false),
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_hollowWithReinforcementOnBothFaces", "_hollowWithReinforcementOnBothFaces", false),
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_longitudinalArea", "_longitudinalArea", false),
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_perimeter", "_perimeter", false),
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_source", "_source", false),
                Field("GPC.Model.Sections.Concrete.ConcreteTorsionData", "_wallThickness", "_wallThickness", false));
            Register("GPC.Model.Sections.SectionTorsionProperties", "GPC.Model.Sections.SectionTorsionProperties",
                Field("GPC.Model.Sections.SectionTorsionProperties", "<Elements>k__BackingField", "<Elements>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<Error>k__BackingField", "<Error>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<Iterations>k__BackingField", "<Iterations>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<MeshSize>k__BackingField", "<MeshSize>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<Nodes>k__BackingField", "<Nodes>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<Parts>k__BackingField", "<Parts>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<ShearCenter>k__BackingField", "<ShearCenter>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<TorsionConstant>k__BackingField", "<TorsionConstant>k__BackingField", false),
                Field("GPC.Model.Sections.SectionTorsionProperties", "<WarpingConstant>k__BackingField", "<WarpingConstant>k__BackingField", false));
            Register("GPC.Model.Sections.SectionVariation", "GPC.Model.Sections.SectionVariation",
                Field("GPC.Model.Sections.SectionVariation", "<End>k__BackingField", "<End>k__BackingField", false),
                Field("GPC.Model.Sections.SectionVariation", "<Law>k__BackingField", "<Law>k__BackingField", false),
                Field("GPC.Model.Sections.SectionVariation", "<Start>k__BackingField", "<Start>k__BackingField", false),
                Field("GPC.Model.Sections.SectionVariation", "_end", "_end", false),
                Field("GPC.Model.Sections.SectionVariation", "_start", "_start", false));
            Register("GPC.Model.Standards.GeotechnicalActionFactors", "GPC.Model.Standards.GeotechnicalActionFactors",
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<Name>k__BackingField", "<Name>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<NonStructuralFavourable>k__BackingField", "<NonStructuralFavourable>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<NonStructuralUnfavourable>k__BackingField", "<NonStructuralUnfavourable>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<PermanentFavourable>k__BackingField", "<PermanentFavourable>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<PermanentUnfavourable>k__BackingField", "<PermanentUnfavourable>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<VariableFavourable>k__BackingField", "<VariableFavourable>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalActionFactors", "<VariableUnfavourable>k__BackingField", "<VariableUnfavourable>k__BackingField", false));
            Register("GPC.Model.Standards.GeotechnicalMaterialFactors", "GPC.Model.Standards.GeotechnicalMaterialFactors",
                Field("GPC.Model.Standards.GeotechnicalMaterialFactors", "<EffectiveCohesion>k__BackingField", "<EffectiveCohesion>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalMaterialFactors", "<Name>k__BackingField", "<Name>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalMaterialFactors", "<TanFrictionAngle>k__BackingField", "<TanFrictionAngle>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalMaterialFactors", "<UnconfinedStrength>k__BackingField", "<UnconfinedStrength>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalMaterialFactors", "<UndrainedShearStrength>k__BackingField", "<UndrainedShearStrength>k__BackingField", false),
                Field("GPC.Model.Standards.GeotechnicalMaterialFactors", "<UnitWeight>k__BackingField", "<UnitWeight>k__BackingField", false));
            Register("GPC.Model.UnitsSystem", "GPC.Model.UnitsSystem",
                Field("GPC.Model.UnitsSystem", "<ForceUnits>k__BackingField", "<ForceUnits>k__BackingField", false),
                Field("GPC.Model.UnitsSystem", "<LengthUnits>k__BackingField", "<LengthUnits>k__BackingField", false),
                Field("GPC.Model.UnitsSystem", "<MassUnits>k__BackingField", "<MassUnits>k__BackingField", false),
                Field("GPC.Model.UnitsSystem", "<PressureUnits>k__BackingField", "<PressureUnits>k__BackingField", false),
                Field("GPC.Model.UnitsSystem", "<TemperatureUnits>k__BackingField", "<TemperatureUnits>k__BackingField", false));
        }
    }
}
